const { NODE_ENV, REACT_APP_WEBSITE_NAME, REACT_APP_API_CURRENCY_EXCHANGE_URL } = process.env;
const env = {
  NODE_ENV,
  API_CURRENCY_EXCHANGE_URL: REACT_APP_API_CURRENCY_EXCHANGE_URL,
  WEBSITE_NAME: REACT_APP_WEBSITE_NAME,
};
export default env;
